name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: h4ks-com/k3s-deploy/.github/workflows/k3s-deploy.yaml@main
    with:
      contexts: "."
      images: "webcapture-service"
